language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python3 scraper.py
  -git config --global user.name "bonfy"
  -git config --global user.email "foreverbonfy@163.com"
  
  -git add -A
  -git commit -m $(date '+%Y-%m-%d')
  -git push

env:
  global:
  - GH_REF: github.com/songjianzaina/travis-test.git
  #设置GH_REF,换成自己用户名和仓库名
